set autoindent autowrite 
set showmatch 
set wrapmargin=0 report=1
set expandtab
set shiftwidth=4
set tabstop=4
set nowrap
set visualbell
syntax on
set history=1000
set nobackup

" These two lines work around a problem with msys ssh.exe, tmux, and vertical split
set columns-=1
autocmd VimResized *   set columns-=1

" This following section uses material from the "Edit_gpg_encrypted_files" article on the vim wiki at Wikia and is licensed under the Creative Commons Attribution-Share Alike License.
" Don't save backups of *.gpg files
set backupskip+=*.gpg

" To avoid that parts of the file is saved to .viminfo when yanking or
" deleting, empty the 'viminfo' option.
set viminfo=
augroup encrypted
  au!
  " Disable swap files, and set binary file format before reading the file
  autocmd BufReadPre,FileReadPre *.gpg
    \ setlocal noswapfile bin
  " Decrypt the contents after reading the file, reset binary file format
  " and run any BufReadPost autocmds matching the file name without the .gpg
  " extension
  autocmd BufReadPost,FileReadPost *.gpg
    \ execute "'[,']!gpg --decrypt --default-recipient-self" |
    \ setlocal nobin |
    \ execute "doautocmd BufReadPost " . expand("%:r")
  " Set binary file format and encrypt the contents before writing the file
  autocmd BufWritePre,FileWritePre *.gpg
    \ setlocal bin |
    \ '[,']!gpg --encrypt --default-recipient-self
  " After writing the file, do an :undo to revert the encryption in the
  " buffer, and reset binary file format
  autocmd BufWritePost,FileWritePost *.gpg
    \ silent u |
    \ setlocal nobin
augroup END
